# yaml-language-server: $schema=<https://canary.uniform.app/schemas/json-schema/component-definition/v1.json>
$schema: https://canary.uniform.app/schemas/json-schema/component-definition/v1.json
id: productDetailsPage
name: Product Details Page
icon: file-document
parameters:
  - id: pageTitle
    name: Page Title
    type: text
    helpText: ''
    typeConfig:
      required: true
  - id: group_metaData
    name: Meta Data
    type: group
    typeConfig:
      childrenParams:
        - pageMetaDescription
        - pageKeywords
  - id: pageMetaDescription
    name: Page Meta Description
    type: text
    helpText: ''
    typeConfig:
      multiline: true
      linesCount: '5'
  - id: pageKeywords
    name: Page Keywords
    type: text
    helpText: ''
    typeConfig:
      multiline: true
  - id: group_openGraph
    name: Open Graph
    type: group
    typeConfig:
      childrenParams:
        - openGraphTitle
        - openGraphImage
        - openGraphType
        - openGraphDescription
        - overlayTitleToOgImage
  - id: openGraphTitle
    name: Open Graph Title
    type: text
    helpText: page head title
    typeConfig: null
  - id: openGraphDescription
    name: Open Graph Description
    type: text
    helpText: >-
      used to set `og:description`. If not set, `Page Meta Description` will be
      used.
    typeConfig:
      multiline: true
      linesCount: '5'
  - id: openGraphImage
    name: Open Graph Image
    type: image
    helpText: This will set og:image
    typeConfig: null
  - id: overlayTitleToOgImage
    name: Overlay Title over Open Graph Image?
    type: checkbox
    helpText: if set, renders the `og:title` over the image dynamically
    typeConfig: null
  - id: openGraphType
    name: Open Graph Type
    type: select
    helpText: sets the value of `og:type` (defalts to "website" if not specified)
    typeConfig:
      options:
        - text: website
          value: website
        - text: video
          value: video
        - text: article
          value: article
  - id: group_twitter
    name: Twitter
    type: group
    typeConfig:
      childrenParams:
        - twitterDescription
        - twitterTitle
        - twitterImage
        - overlayTitleToTwitterImage
        - twitterCard
  - id: twitterTitle
    name: Twitter Title
    type: text
    helpText: Sets `twitter:title`. Fallback to Page Title if not set.
    typeConfig: null
  - id: twitterDescription
    name: Twitter Description
    type: text
    helpText: >-
      Sets `twitter:description`. Falls back to `Page Meta Description` if not
      set
    typeConfig:
      multiline: true
      linesCount: '5'
  - id: twitterImage
    name: Twitter Image
    type: image
    helpText: Sets `twitter:image`. Fallsback to `og:image` if not set.
    typeConfig: null
  - id: overlayTitleToTwitterImage
    name: Overlay Title to Twitter Image?
    type: checkbox
    helpText: if set, overlays content of `twitter:title` over the image dynamically
    typeConfig: null
  - id: twitterCard
    name: Twitter Card
    type: select
    helpText: Sets the value of `twitter:card`. If not set, defaults to `summary`.
    typeConfig:
      options:
        - text: summary
          value: summary
        - text: summary_large_image
          value: summary_large_image
        - text: app
          value: app
        - text: player
          value: player
categoryId: 31fcffb0-aead-4256-8e49-4d50cc28aa29
previewImageUrl: >-
  https://res.cloudinary.com/uniform-demos/image/upload/v1/csk-preview-images/UniformTheme/page_preview_image
useTeamPermissions: true
slots:
  - id: pageHeader
    name: Page Header
    maxComponents: 1
    minComponents: 1
    allowedComponents:
      - header
    allowAllComponents: false
    inheritAllowedComponents: false
    patternsInAllowedComponents: false
  - id: pageContent
    name: Page Content
    allowedComponents:
      - spacer
      - cardBlock
      - $p:4e0d0103-d14c-4792-9772-7948a3701a4c
      - $p:7f209571-9934-4219-ba2a-72afd062f04f
      - divider
      - hero
      - productDetails
      - $p:4f6e4ec8-439d-4d8f-91ba-155afb898d41
      - breadcrumbs
      - productGallery
      - productInfo
      - container
      - grid
      - accordion
      - $p:f0a81998-50d1-4a24-b0e8-07ae3df85706
      - $p:1557eb38-f322-406a-8509-0e91ae24b50e
    allowAllComponents: false
    inheritAllowedComponents: false
    patternsInAllowedComponents: true
  - id: pageFooter
    name: Page Footer
    maxComponents: 1
    allowedComponents:
      - footer
    allowAllComponents: false
    inheritAllowedComponents: false
    patternsInAllowedComponents: false
defaults:
  type: productDetailsPage
  slots:
    pageFooter:
      - type: footer
        _pattern: 319639e9-4bac-4fb3-8f0b-19088c969fcb
    pageHeader:
      - type: header
        _pattern: e46c8336-acfd-43e8-ac59-8be8f4c33b7d
        _overridability:
          parameters:
            syntheticGap: 'yes'
  parameters:
    pageTitle:
      type: text
      value: Product Details Page
  _dataResources: {}
titleParameter: pageTitle
canBeComposition: true
created: '2023-09-26T08:46:46.998703+00:00'
updated: '2023-09-26T08:46:46.998703+00:00'
